name: Wiki_sync_to_devDocs
# Synchronisiert ./docs mit Wiki (info:https://github.com/newrelic/wiki-sync-action/tree/main)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: SpacerX
  GIT_AUTHOR_EMAIL: rbe@spacerx.de

jobs:
  job-sync-wiki-to-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RBE_TOKEN }} # allows us to push back to repo
          ref: dev

      # from main (requiere: Dockerfile, action.yml, entrypoint.sh)
      #- name: Sync wiki to docs 
      #  uses: SpacerX/Sync-DocsAndWiki-Actions@main  
        
      # from Marketplace (Bi-directional Wiki Sync Action)
      - name: Sync wiki to docs
        uses: newrelic/wiki-sync-action@v1.0.1     
        with:
          branch: dev
          source: wiki
          destination: docs
          token: ${{ secrets.RBE_TOKEN }}
          gitAuthorName: ${{ env.GIT_AUTHOR_NAME }}
          gitAuthorEmail: ${{ env.GIT_AUTHOR_EMAIL }}
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
